services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: node:18-alpine
    working_dir: /app
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

volumes:
  postgres_data: 